# TODO use .env file for environment variables
version: "3.8"

services:
  parcel_delivery_dev_db:
    container_name: parcel_delivery_dev_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: dev_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata_parcel_delivery_dev_db:/var/lib/postgresql/data
    restart: always

  parcel_delivery_test_db:
    container_name: parcel_delivery_test_db
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: test_db
    ports:
      - "8433:5432"
    volumes:
      - pgdata_parcel_delivery_test_db:/var/lib/postgresql/data
    restart: always

  exchange:
    container_name: exchange
    image: postgres:13
    environment:
      POSTGRES_USER: stroka01
      POSTGRES_PASSWORD: user
      POSTGRES_DB: exchange_db
    ports:
      - "8434:5432"
    volumes:
      - exchange_db:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  pgdata_parcel_delivery_dev_db: {}
  pgdata_parcel_delivery_test_db: {}
  exchange_db: {}
  cache: {}

networks:
  default:
    name: my_network
    driver: bridge
